# Настройки сборки и деплоя для Netlify
[build]
  # Директория, в которой выполняется команда сборки
  base = "/"

  # Команда для сборки проекта
  command = "npm run build"

  # Директория, в которую собирается проект (зависит от настроек Vite)
  publish = "dist"

# Настройки для SPA - перенаправление всех запросов на index.html
# Это необходимо для корректной работы React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки заголовков для безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.taskmaster.example; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https://images.unsplash.com https://ui-avatars.com; font-src 'self' https://cdnjs.cloudflare.com;"

# Настройки для кеширования статических ресурсов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Настройки для Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Настройки плагинов Netlify (опционально)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true